
export const levelUpMessages: Record<string, { icon: string; message: string }> = {
    'Listener': { icon: '🎧', message: 'You’ve become a Listener! Keep tuning your heart to God’s Word.' },
    'Seeker': { icon: '🔍', message: 'You’re now a Seeker! God promises you will find Him as you seek.' },
    'Apprentice of the Word': { icon: '📖', message: 'You’re an Apprentice of the Word! Keep growing strong in salvation.' },
    'Scripture Explorer': { icon: '🕯️', message: 'You’re a Scripture Explorer! God’s Word is lighting your path.' },
    'Faith Builder': { icon: '🏗️', message: 'You’re a Faith Builder! Keep building yourself up in holy faith.' },
    'Disciple-in-Training': { icon: '✝️', message: 'You’re a Disciple-in-Training! Take up your cross daily and follow Him.' },
    'Light Bearer': { icon: '💡', message: 'You’re a Light Bearer! Shine so others see God’s glory.' },
    'Word Worker': { icon: '🛠️', message: 'You’re a Word Worker! Handle the Word of truth with confidence.' },
    'Servant Leader': { icon: '🤝', message: 'You’re a Servant Leader! True greatness comes through serving.' },
    'Armor Bearer': { icon: '🛡️', message: 'You’re an Armor Bearer! Stand firm in God’s strength.' },
    'Shepherd’s Friend': { icon: '🐑', message: 'You’re a Shepherd’s Friend! Follow the Good Shepherd’s lead.' },
    'Fruitful Branch': { icon: '🌿', message: 'You’re a Fruitful Branch! Stay connected to Jesus and bear fruit.' },
    'Mountain Mover': { icon: '⛰️', message: 'You’re a Mountain Mover! Nothing is impossible with faith.' },
    'Living Stone': { icon: '🧱', message: 'You’re a Living Stone! God is building you into His house.' },
    'Kingdom Builder': { icon: '👑', message: 'You’re a Kingdom Builder! Keep seeking His kingdom first.' },
    'Fisher of People': { icon: '🎣', message: 'You’re a Fisher of People! Cast the net of God’s love wide.' },
    'Overcomer': { icon: '🏆', message: 'You’re an Overcomer! Jesus has conquered the world — take heart.' },
    'Good and Faithful Servant': { icon: '🌟', message: 'Well done, Good and Faithful Servant! Share your Master’s joy.' },
    'Pillar of the Church': { icon: '🏛️', message: 'You’re a Pillar of the Church! Stand firm and strengthen others.' },
    'Crown of Life': { icon: '👑', message: 'You’ve earned the Crown of Life! Remain steadfast under trial.' },
    'Light to the Nations': { icon: '🌍', message: 'You are a Light to the Nations! God’s salvation shines through you.' },
};
